### ISSUE TITLE
Cant build: github.com/chrisccoulson/secboot not available anymore

### ISSUE THREAD

**Issue by Itxaka** [canonical/nullboot#28]
If you clone the main branch and try to build, it will fail as the repo `github.com/chrisccoulson/secboot` which replaces `github.com/snapcore/secboot` is now empty:

```
$ go build cmd/nullbootctl/main.go 
go: github.com/snapcore/secboot@v0.0.0-20220406084634-6e724131009b (replaced by github.com/chrisccoulson/secboot@v0.0.0-20211101133820-41f32b803753): version "v0.0.0-20211101133820-41f32b803753" invalid: unknown revision 41f32b803753
go: downloading github.com/chrisccoulson/secboot v0.0.0-20211101133820-41f32b803753
go: github.com/snapcore/secboot@v0.0.0-20220406084634-6e724131009b (replaced by github.com/chrisccoulson/secboot@v0.0.0-20211101133820-41f32b803753): version "v0.0.0-20211101133820-41f32b803753" invalid: unknown revision 41f32b803753
```

This used to work, but the `github.com/chrisccoulson/secboot` fork is now empty

**Comment by julian-klode** [comment]
Confirmed. That's a bit annoying @chrisccoulson, can you fix that, at least push a branch back to that repo with the commit in it, so the repo builds again?

The package is of course fine as it builds a vendor tarball during git export:
https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/nullboot/0.4.0-0ubuntu1/nullboot_0.4.0.orig-vendor.tar.gz

I'd really like to move to you know real releases of those dependencies rather than hacked up local branches.

**Comment by chrisccoulson** [comment]
The repo isn't empty - it looks like what happened is I force pushed to this branch because it was originally created for https://github.com/snapcore/secboot/pull/183 which sat around for ages until I updated it again recently.

**Comment by chrisccoulson** [comment]
Fortunately, it looks like I still have that commit in my local repo, so I've pushed it to another branch: https://github.com/chrisccoulson/secboot/commit/41f32b803753e6b9d3d37b4b68c2e4c7171197fe

**Comment by Itxaka** [comment]
can confirm that now its possible to build it again, thanks @chrisccoulson !
